name: Bug report
description: Report a reproducible bug.
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
    validations:
      required: true
